[2024-02-23T20:33:37.296+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: my_dag.training_model_A manual__2024-02-23T20:32:28.652999+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
