[2024-03-06T12:43:33.495+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: weather_dag.transform_load_weather_data manual__2024-03-06T12:28:36.871582+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
