[2024-03-06T11:05:57.849+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: weather_dag.is_weather_api_ready manual__2024-03-05T22:09:36.606887+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
