[2024-03-06T20:57:48.105+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: weather_dag.extract_weather_data manual__2024-03-06T20:40:44.349998+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
