[2024-02-23T20:33:37.614+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: my_dag.training_model_C scheduled__2024-02-22T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
